trigger:
  branches:
    include:
      - master
pr:
  branches:
    include:
      - master
variables:
  version: 1.0.1
  appArtifactName: app
  testsArtifactName: tests
stages:
  - stage: Build
    displayName: 'Build projects'
    jobs:
      - job: SetVersion
        steps:
          - script: echo "##vso[build.updatebuildnumber]$(version)"
      - template: .pipelines/build.job.yml
        parameters:
          jobName: BuildApp
          projectDirectory: src/Poli.App
          projectFile: Poli.App.csproj
          artifactName: $(appArtifactName)
          version: $(version)
          publish: true
      - template: .pipelines/build.job.yml
        parameters:
          jobName: BuildTests
          projectDirectory: test/Poli.App.Tests
          projectFile: Poli.App.Tests.csproj
          artifactName: $(testsArtifactName)
          version: $(version)
  - stage: Test
    displayName: 'Test output'
    dependsOn: Build
    jobs:
      - template: .pipelines/test.job.yml
        parameters:
          jobName: RunTests
          artifactName: $(testsArtifactName)
  - stage: Deploy
    displayName: Deploy
    dependsOn: Test
    jobs:
      - deployment: App
        environment: App
        variables:
          artifactDownloadLocation: '$(System.DefaultWorkingDirectory)/artifact_downloads'
          appServiceName: poli-alessandro-app-we-app
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                    artifactName: $(appArtifactName)
                    targetPath: $(artifactDownloadLocation)
                - task: AzureRmWebAppDeployment@4
                  inputs:
                    ConnectionType: AzureRM
                    azureSubscription: Alessandro
                    appType: webApp
                    WebAppName: $(appServiceName)
                    packageForLinux: '$(artifactDownloadLocation)/**/*.zip'
          