trigger:
  branches:
    include:
      - master
pr:
  branches:
    include:
      - master
variables:
  version: 1.0.1
stages:
  - stage: Build
    displayName: 'Build projects'
    jobs:
      - job: SetVersion
        steps:
          - script: echo "##vso[build.updatebuildnumber]$(version)"
      - template: .pipelines/build.job.yml
        parameters:
          jobName: BuildApp
          projectDirectory: src/Poli.App
          projectFile: Poli.App.csproj
          artifactName: app
          version: $(version)
          publish: true
      - template: .pipelines/build.job.yml
        parameters:
          jobName: BuildTests
          projectDirectory: test/Poli.App.Tests
          projectFile: Poli.App.Tests.csproj
          artifactName: tests
          version: $(version)
  - stage: Test
    displayName: 'Test output'
    dependsOn: Build
    jobs:
      - template: .pipelines/test.job.yml
        parameters:
          jobName: RunTests
          artifactName: tests
          