trigger:
  branches:
    include:
      - master
pr:
  branches:
    include:
      - master
variables:
  version: 1.0.1
stages:
  - stage: Build
    displayName: 'Build projects'
    jobs:
      - template: .pipelines/build.job.yml
        parameters:
          jobName: BuildApp
          projectDirectory: src/Poli.App
          projectFile: Poli.App.csproj
          artifactName: app
          version: $(version)
          publish: true
      - template: .pipelines/build.job.yml
        parameters:
          jobName: BuildTests
          projectDirectory: test/Poli.App.Tests
          projectFile: Poli.App.Tests.csproj
          artifactName: tests
          version: $(version)