steps:
  - task: DotNetCoreCLI@2
    displayName: 'Restore packages'
    inputs:
      command: restore
  - task: DotNetCoreCLI@2
    displayName: 'Build project'
    inputs:
      command: build
      configuration: Release
      buildProperties: '/p:Version=1.0.1'
  - task: PublishPipelineArtifact@1
    displayName: 'Publish artifact'
    inputs:
      targetPath: bin/Release/netcoreapp3.0
      artifact: Release
