trigger:
  branches:
    include:
      - fake_master
pr:
  branches:
    include:
      - fake_master
jobs:
  - job: Build
    displayName: Build and publish artifacts
    pool:
      vmImage: windows-latest
    steps:
      - task: DotNetCoreCLI@2
        displayName: 'Restore packages'
        inputs:
          command: restore
      - task: DotNetCoreCLI@2
        displayName: 'Build project'
        inputs:
          command: build
          arguments: '--configuration Release /p:Version=1.0.1 --no-restore'
      - task: DotNetCoreCLI@2
        displayName: 'Publish project'
        inputs:
          command: publish
          publishWebProjects: True
          arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory) --no-build'
          zipAfterPublish: True
      - task: PublishPipelineArtifact@1
        displayName: 'Publish artifact'
        inputs:
          targetPath: $(Build.ArtifactStagingDirectory)
          artifact: website
