trigger:
  branches:
    include:
      - master
pr:
  branches:
    include:
      - master
stages:
  - stage: Build
    displayName: 'Build projects'
    jobs:
      - template: .pipelines/build.job.yml
        parameters:
          jobName: BuildApp
          projectPath: src/Poli.App/Poli.App.csproj
          configuration: Release
          artifactName: app
          artifactDirectory: output/app
          version: 1.0.1
          publish: true
      - template: .pipelines/build.job.yml
        parameters:
          jobName: BuildTests
          projectPath: test/Poli.App.Tests/Poli.App.Tests.csproj
          configuration: Release
          artifactName: tests
          artifactDirectory: output/tests
          version: 1.0.1