parameters:
  jobName: null
  projectDirectory: null
  projectFile: null
  artifactName: null
  version: null
  publish: false
  configuration: Release
  publishRuntime: win-x64
jobs:
  - job: ${{ parameters.jobName }}
    displayName: ${{ parameters.jobName }}
    pool:
      vmImage: windows-latest
    steps:
      - task: DotNetCoreCLI@2
        displayName: 'Restore packages'
        inputs:
          command: restore
          projects: '${{ parameters.projectDirectory }}/${{ parameters.projectFile }}'
      - task: DotNetCoreCLI@2
        displayName: 'Build project'
        inputs:
          command: build
          arguments: '--configuration ${{ parameters.configuration }} /p:Version=${{ parameters.version }} --no-restore'
          projects: '${{ parameters.projectDirectory }}/${{ parameters.projectFile }}'
      - task: DotNetCoreCLI@2
        displayName: 'Publish project'
        condition: eq('${{ parameters.publish }}', 'true')
        inputs:
          command: publish
          arguments: '--configuration ${{ parameters.configuration }} --self-contained --runtime ${{ parameters.publishRuntime }} --no-build'
          projects: '${{ parameters.projectDirectory }}/${{ parameters.projectFile }}'
      - task: PublishPipelineArtifact@1
        displayName: 'Publish artifact'
        condition: eq('${{ parameters.publish }}', 'true')
        inputs:
          targetPath: '${{ parameters.projectDirectory }}/bin/${{ parameters.configuration }}/netcoreapp3.0/${{ parameters.publishRuntime }}'
          artifact: ${{ parameters.artifactName }}
      - task: PublishPipelineArtifact@1
        displayName: 'Publish artifact'
        condition: ne('${{ parameters.publish }}', 'true')
        inputs:
          targetPath: '${{ parameters.projectDirectory }}/bin/${{ parameters.configuration }}/netcoreapp3.0'
          artifact: ${{ parameters.artifactName }}
