parameters:
  jobName: null
  projectPath: null
  configuration: null
  artifactName: null
  version: null
  publish: false
variables:
  outputPath: bin
jobs:
  - job: ${{ parameters.jobName }}
    displayName: ${{ parameters.jobName }}
    pool:
      vmImage: windows-latest
    steps:
      - task: DotNetCoreCLI@2
        displayName: 'Restore packages'
        inputs:
          command: restore
          projects: ${{ parameters.projectPath }}
      - task: DotNetCoreCLI@2
        displayName: 'Build project'
        inputs:
          command: build
          arguments: '--configuration ${{ parameters.configuration }} /p:Version=${{ parameters.version }} --output $(outputPath) --no-restore'
          projects: ${{ parameters.projectPath }}
      - task: DotNetCoreCLI@2
        displayName: 'Publish project'
        condition: eq('${{ parameters.publish }}', 'true')
        inputs:
          command: publish
          arguments: '--configuration ${{ parameters.configuration }} --output $(outputPath) --no-build'
          projects: ${{ parameters.projectPath }}
      - task: PublishPipelineArtifact@1
        displayName: 'Publish artifact'
        inputs:
          targetPath: $(outputPath)
          artifact: ${{ parameters.artifactName }}
