parameters:
  deploymentName: null
  environmentName: null
  artifactDownloadLocation: '$(System.DefaultWorkingDirectory)/artifact_downloads'
  resourceGroupName: null
  resourceGroupLocation: null
  artifactName: null
  azureConnectionName: null
  templateFile: null
  parametersFile: null
jobs:
  - deployment: ${{ parameters.deploymentName }}
    environment: ${{ parameters.environmentName }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadPipelineArtifact@2
              inputs:
                artifactName: ${{ parameters.artifactName }}
                targetPath: ${{ parameters.artifactDownloadLocation }}

            - powershell: |
                Get-ChildItem $ENV:artifactDownloadLocation -Recurse | ForEach-Object { $_.FullName }
              env:
                artifactDownloadLocation: ${{ parameters.artifactDownloadLocation }}
              
            - task: AzurePowerShell@4
              inputs:
                azureSubscription: ${{ parameters.azureConnectionName }}
                Inline: |
                  New-AzureRmResourceGroup -Name ${{ parameters.resourceGroupName }} -Location ${{ parameters.resourceGroupLocation }} -Tag @{ Owner = "alessandro@uipath.com"; Project = "Poli"; }

            - task: AzureResourceGroupDeployment@2
              inputs:
                azureSubscription: ${{ parameters.azureConnectionName }}
                resourceGroupName: ${{ parameters.resourceGroupName }}
                location: ${{ parameters.location }}
                templateLocation: ${{ parameters.artifactDownloadLocation }}/${{ parameters.templateFile }}
                csmParametersFile: ${{ parameters.artifactDownloadLocation }}/${{ parameters.parametersFile }}
