parameters:
  jobName: null
  artifactName: null
jobs:
  - job: ${{ parameters.jobName }}
    displayName: ${{ parameters.jobName }}
    pool:
      vmImage: windows-latest
    steps:
      - checkout: none
      - task: DownloadPipelineArtifact@2
        inputs:
          artifactName: ${{ parameters.artifactName }}
      - script: |
          dotnet vstest **/*.Tests.dll
