parameters:
  jobName: null
  artifactName: null
  artifactDownloadPath: artifact_downloads
  testAssembliesPattern: '**/*.Tests.dll'
  testLogFileName: Tests.trx
jobs:
  - job: ${{ parameters.jobName }}
    displayName: ${{ parameters.jobName }}
    pool:
      vmImage: windows-latest
    steps:
      - checkout: none
      - task: DownloadPipelineArtifact@2
        inputs:
          artifactName: ${{ parameters.artifactName }}
          targetPath: ${{ parameters.artifactDownloadPath }}
      - script: |
          dotnet vstest ${{ parameters.artifactDownloadPath }}/${{ parameters.testAssembliesPattern }} /logger:trx;${{ parameters.testLogFileName }}
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testRunner: VSTest
          testResultsFiles: '**/*.trx'