parameters:
  jobName: null
  artifactName: null
  artifactDownloadPath: artifact_downloads
jobs:
  - job: ${{ parameters.jobName }}
    displayName: ${{ parameters.jobName }}
    pool:
      vmImage: windows-latest
    steps:
      - checkout: none
      - task: DownloadPipelineArtifact@2
        inputs:
          artifactName: ${{ parameters.artifactName }}
          targetPath: ${{ parameters.artifactDownloadPath }}
      - script: |
          dotnet vstest ${{ parameters.artifactDownloadPath }}/**/*.Tests.dll --logger trx
      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testRunner: VSTest
          testResultsFiles: '**/*.trx'